### PR TITLE
Online events

### PR DESCRIPTION
**Pull request by LeonVreling**

### CODE REVIEW

**Comment by LeonVreling** [comment]
@serge1peshcoff  this updates the messages on the pop-up to also display the times of the event, and breaks the title onto a new line when it is too long

**Comment by serge1peshcoff** [comment]
@LeonVreling can you rebase on master so it won't include commits merge already?

**Comment by LeonVreling** [comment]
> @LeonVreling can you rebase on master so it won't include commits merge already?

Uhm what do you mean? 😅

**Comment by serge1peshcoff** [comment]
@LeonVreling  `git rebase -i origin/master`, also check out https://git-scm.com/book/en/v2/Git-Branching-Rebasing, this can be quite useful. For now there are commits that are merged already, we can get rid of them by using rebase.

**Comment by LeonVreling** [comment]
@serge1peshcoff it took some time and a few attempts, but I think it is all good now

**Pull request merged**
