### PR TITLE
Added alastair frontend

### PR DESCRIPTION
**Pull request by serge1peshcoff**
Supersedes the current one (basically rebased it on master, changed the commit messages and resolved merge conflicts).

### CODE REVIEW

**Comment by serge1peshcoff** [comment]
@blacksph3re no idea why I can't assign you as reviewer, can you check if everything is okay here?

**Comment by serge1peshcoff** [comment]
I've also updated the frontend to match the eslint code style, no idea if it would work, can you check?

**Comment by blacksph3re** [comment]
Yep works, thanks a lot! Can you merge?

**Comment by serge1peshcoff** [comment]
@blacksph3re yep, will do in 1 commit and 2 passed checks

**Comment by blacksph3re** [comment]
Can I deploy or is there anything I should watch out for?

**Comment by serge1peshcoff** [comment]
@blacksph3re to the production?

**Pull request merged**
