### PR TITLE
fix(alasair): Shop-Modal didn't open

### PR DESCRIPTION
**Pull request by blacksph3re**
Fixed some problems with shop assignments

### CODE REVIEW

**Comment by serge1peshcoff** [comment]
@blacksph3re can you do a few things first?
1) fix the name of the commit (`alastair` instead `alasair`)
2) update Axios to latest to fix security vulnerability and add it as another commit
3) run `npm version patch` after it to bump patch version

**Comment by blacksph3re** [comment]
Ah fuck, my amend got lost :/

**Comment by serge1peshcoff** [comment]
@blacksph3re and also follow the conventional commits names schema for new commits :D

**Comment by blacksph3re** [comment]
:D fuck

**Comment by serge1peshcoff** [comment]
@blacksph3re you can use rebase and reword for it, worked for me

**Comment by blacksph3re** [comment]
it's rather difficult to rename commits

**Comment by serge1peshcoff** [comment]
can you bump the version as well? no need to commit anything, it's done automatically by running `npm version patch`

**Comment by blacksph3re** [comment]
I tried but it crashed... don't know, probably not :D It said something with not a git repository

**Comment by serge1peshcoff** [comment]
did you do it on oms-frontend/ folder?
if yes, can you provide logs?

**Comment by blacksph3re** [comment]
In the folder directly:
```
v0.15.2

> oms-frontend@0.15.2 version /home/sph3re/Programming/oms-docker-2/oms-frontend
> conventional-changelog -p angular -i CHANGELOG.md -s -r 0 && git add CHANGELOG.md

sh: conventional-changelog: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! oms-frontend@0.15.2 version: `conventional-changelog -p angular -i CHANGELOG.md -s -r 0 && git add CHANGELOG.md`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the oms-frontend@0.15.2 version script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```
In the container:
```
ontend npm version patch
v0.15.3
npm WARN lifecycle oms-frontend@0.15.3~version: cannot run in wd oms-frontend@0.15.3 conventional-changelog -p angular -i CHANGELOG.md -s -r 0 && git add CHANGELOG.md (wd=/usr/app/src)
npm ERR! code 128
npm ERR! Command failed: git add /usr/app/src/package.json
npm ERR! fatal: Not a git repository: ../.git/modules/oms-frontend
npm ERR! 

```

**Comment by serge1peshcoff** [comment]
ah I know.
try running `npm i` in the root folder

**Comment by serge1peshcoff** [comment]
if that won't work try `npm i -G conventional-changelog-cli`

**Comment by serge1peshcoff** [comment]
(I wonder why didn't I put it as a dependency here...)

**Comment by blacksph3re** [comment]
the last line helped

**Comment by serge1peshcoff** [comment]
dafuq is going with changelog :D
I'll rebase it and fix it when I'll get home

**Comment by blacksph3re** [comment]
But it worked now?

**Comment by serge1peshcoff** [comment]
@blacksph3re yep but it bumped 5 versions instead of one and fucked up the changelog :D no idea why, will investigate

**Comment by blacksph3re** [comment]
okay, thanks :)

**Comment by blacksph3re** [comment]
did you find the problem already?

**Comment by serge1peshcoff** [comment]
nope, I was (and still am) figuring out how to use Ansible to deploy TeamCity to pipeline. after that I'll check other things

**Comment by blacksph3re** [comment]
Ah okay, yeah the bugs here aren't breaking anything anyways. Cool :)

**Comment by serge1peshcoff** [comment]
Will make another PR based on that and rebased properly.

**Pull request closed without merging**
