### PR TITLE
Dashboard split events

### PR DESCRIPTION
**Pull request by LeonVreling**
-Split the events on the dashboard by upcoming and past events
-Add statutory events to the list of events you have applied for
-Sort all events on dashboard based on date

Corresponds with [MEMB-825](https://myaegee.atlassian.net/browse/MEMB-825)

### CODE REVIEW

**Comment by LeonVreling** [comment]
@serge1peshcoff my javascript knowledge is not good enough to fix this lint error. I think it just doesn't like that I'm using an inline function with an inline if statement combined.

**Comment by serge1peshcoff** [comment]
For ESLint, let's check it it'll be an issue after this is done

**Comment by linuxbandit** [comment]
Nice one Leon!

**Comment by serge1peshcoff** [comment]
I'll merge after merging new event types by Maaike. Will do tonight anyway.

**Pull request merged**
