### PR TITLE
fix(resources): CIA link to category. Fixes HELP-671

### PR DESCRIPTION
**Pull request by WikiRik**

### CODE REVIEW

**Comment by serge1peshcoff** [comment]
@WikiRik can you rebase and force-push to trigger CI? it didn't finish for some reason, then I'll merge

**Comment by WikiRik** [comment]
Rebasing for some reason did not work, but I forgot that I wanted to do what I did in the new commit for consistency

**Comment by WikiRik** [comment]
Not sure what GitHub is doing, I can see the checks being performed here: https://github.com/AEGEE/oms-frontend/pull/355/checks?check_run_id=661343483

**Comment by serge1peshcoff** [comment]
whatever, I'll merge anyway, I can do anything as an admin

**Pull request merged**
