### PR TITLE
chore(footer): ui changes. Fixes MEMB-432

### PR DESCRIPTION
**Pull request by WikiRik**
Fixed the comments on #290 

@serge1peshcoff did you do stuff with the CORS proxy already?

### CODE REVIEW

**Comment by serge1peshcoff** [comment]
@WikiRik the CORS issue should be fixed, yep

**Comment by serge1peshcoff** [comment]
@WikiRik can I merge and deploy?

**Comment by WikiRik** [comment]
Not sure if the link to Confluence is working now, but there's one way to find out. Let's deploy

**Comment by serge1peshcoff** [comment]
and apparently github isn't feeling well as the checks are not passing. let's wait

**Pull request merged**
