### PR TITLE
(Impr) Dockerfile now is the docker way

### PR DESCRIPTION
**Pull request by linuxbandit**
The source files are copied on build time and not mounted.
This is the way the Dockerfiles should be written. Unfortunately
due to scopes, the Dockerfile cannot be inside docker, because
the COPY operation does not go above (..) the Dockerfile position.
Alternative to this could be to 'RUN git clone [....]' but this
approach is too rigid: in the way proposed, the files can still
be modified and the image rebuilt.

### CODE REVIEW

**Comment by serge1peshcoff** [comment]
that'll do for now, but need to refactor later. Did you try running it btw?

**Comment by linuxbandit** [comment]
I did, but before merging everything on every master I want to be pretty damn sure so I will bootstrap again :p

**Comment by linuxbandit** [comment]
frontend is the only one who bothers, for now (also seems that if I put WORKDIR before COPY, it explodes and nginx is completely empty xD)

**Comment by linuxbandit** [comment]
assigned means I am ready to merge, that's all

**Pull request closed without merging**
